Rails.application.routes.draw do
  root 'test#index'
  get 'api/v1/p_headers', to: 'test#p_headers'
  post 'api/v1/login', to: 'user#login'
  get 'api/v1/user', to: 'user#print_all'
  post 'api/v1/user', to: 'user#register'
  get 'api/v1/user/:id', to: 'user#view'
  post 'api/v1/user/:id/subscribe', to: 'user#subscribe'
  delete 'api/v1/user/:id/subscribe', to: 'user#unsubscribe'
  delete 'api/v1/user/:id', to: 'user#kick'
  post 'api/telegramHandler/oTh3r_$lD3', to: 'telegram#index'
  post 'api/v1/post', to: 'post#create'
  post 'api/v1/category', to: 'general#create_category'
  delete 'api/v1/category/:id', to: 'general#delete_category'
  post 'api/v1/post/:id/like', to: 'post#like'
  delete 'api/v1/post/:id/like', to: 'post#dislike'
  delete 'api/v1/post/:id', to: 'post#delete'
  post 'api/v1/post/:id/comment', to: 'comment#create'
  delete 'api/v1/comment/:id', to: 'comment#delete'
  post 'api/v1/comment/:id/reply', to: 'comment#reply'
end
